#!/data/data/com.termux/files/usr/bin/python
import platform,os,sys
bit = platform.architecture()[0]
if bit == '64bit':
    import COMDECOM
elif bit == '32bit':
    print(" [•] This tool is not supported in your device ")
